name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}
        






# Configure matrix strategy to set up a build matrix for this job/step using the below spec:

#   This job should execute on these operating systems - ubuntu-latest, macos-latest, windows-latest
#   Use os as the key to define these operating systems within the matrix.
#   The Set up Python step should install python-version 3.7, 3.8, 3.9
#   Use py-version as the key to define these python-version within the matrix.
#   Modify the job and step to make use of these matrix values.
#   Push and trigger the workflow.